### ISSUE TITLE
solution/workaround to 2. Grant Permissions

### ISSUE THREAD

**Issue by jlsjonas** [matt-filion/serverless-external-s3-event#10]
instead of requiring step 2 manually, you could instead just require/recommend having an appropriate aws setup, and create the command(s) and execute them before doing the actual set-up. Alternatively have a prompt requesting the user to execute the command(s) (pre-filled with correct variables parsed from the serverless.yml) and exit

**Comment by onyxraven** [comment]
This should be resolved on master

**Comment by matt-filion** [comment]
Resolved on master and 2.0
