### ISSUE TITLE
Two API issues with master (empty lambda policy and existing s3 notification)

### ISSUE THREAD

**Issue by onyxraven** [matt-filion/serverless-external-s3-event#13]
1. If the Lambda policy is empty, the AWS api for getPolicy returns a 404 which is currently handled as an error.  Detect this as a empty state and continue.  I've prototyped this by adding a catch and checking `err.statusCode === '404'`

2. It looks like if the putBucketNotificationConfiguration on s3 is exactly the same as it was, the API might return a 400 error.  I'm looking into this one deeper, I think there are a few fixes (including deep-equals and just skipping the api call)

**Comment by matt-filion** [comment]
This should be resolved with 2.0 branch as well as 1.0.6, which was just pushed to NPM. 2.0 I'll wait to push until I get some confirmation from others that it works for them as expected.

**Comment by matt-filion** [comment]
@onyxraven Are you able to confirm if these issues still exist for you, ideally on 2.0~?
