### ISSUE TITLE
Not working with current release of Serverless v1.11.0

### ISSUE THREAD

**Issue by n8sabes** [matt-filion/serverless-external-s3-event#16]
Doesn't seem to attach S3 events when deploying with the current release of Serverless (v1.11.0).

Also tried PR#15 w/o any luck.

**Comment by matt-filion** [comment]
This should be resolved with 2.0 branch as well as 1.0.6, which was just pushed to NPM. 2.0 I'll wait to push until I get some confirmation from others that it works for them as expected.
