### ISSUE TITLE
Already created S3 notifications are removed

### ISSUE THREAD

**Issue by alejobs** [matt-filion/serverless-external-s3-event#21]
Hi,

When running version 2.0.2, if there is already another S3 notification attached to the same bucket, when running:
serverless s3deploy

It removes these previous notifications...

**Comment by matt-filion** [comment]
Unfortunately this is the default behavior of how notifications are updated. http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUTnotification.html

We can get the current notifications and try to preserve them, this will take a bit, so hopefully this isn't to urgent of a need.

**Comment by AndrewFarley** [comment]
FYI, this bug was fixed by my recent merge.  Please try this again @alejobs and confirm.  :)  It should be fine now though.  I saw this also, and needed this behavior fixed for my client.

**Comment by matt-filion** [comment]
Resolving this issue.
