### ISSUE TITLE
ObjectUpdated and ObjectRemoved not working

### ISSUE THREAD

**Issue by ajshukury** [matt-filion/serverless-external-s3-event#28]
When attaching events for objectRemoved and objectUpdated 'sls s3deploy' throw an error: 'this event is not supported for notification s3'. What is the deal? Only objectCreated is supported?

**Comment by matt-filion** [comment]
Can you attach the function definition from your serverless.yml?

**Comment by ajshukury** [comment]
service: xxxx
provider:
  name: aws
  runtime: xxx
  role: arn:aws:iam::xxxx:role/xxx
  iamRoleStatements:
    -  Effect: "Allow"
       Action:
         - "s3:*"
       Resource:
         Fn::Join:
           - ""
           - - "arn:aws:s3:::xxx"
package:
  exclude:
    - tests/**
    - spec/**
    - packages.json
    - serverless.yml
    - node_modules/aws-sdk/**
plugins:
 - serverless-external-s3-event
functions:
  rocketchat:
    handler: services/handler.xxx
    events:
      - existingS3:
          bucket: xxx
          events:
            - s3:ObjectCreated:*
            - s3:ObjectUpdated:*
            - s3:ObjectRemoved:*
          rules:
            - prefix: xxx/
            - suffix: .json

**Comment by ajshukury** [comment]
When I remove below then it works and adds the only event which object created to my s3.
s3:ObjectUpdated:*
s3:ObjectRemoved:*

**Comment by schaumtier** [comment]
it works for me if i write 
```yml
...
          event:
            - s3:ObjectCreated:*
            - s3:ObjectUpdated:*
            - s3:ObjectRemoved:*
...
```
... (`event` instead of `events` - without the `s`)
