### ISSUE TITLE
plugin overrides pre existing s3 events

### ISSUE THREAD

**Issue by beeva-alvarolopez** [matt-filion/serverless-external-s3-event#40]
If the referenced S3 bucket has any prexisting events confgured, after run sls s3deploy, the old events are overrided by the event configured in serverless

**Comment by simonaudet** [comment]
I'm having this error as well. Two deployments of existingS3 events with the same rule whill override each other. Very frustrating.

**Comment by phouse512** [comment]
Just wanted to second that I am seeing this. @matt-filion do you have an idea of what might be causing this? I have some time I could spend looking into it if you can point me to a starting point.
