### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by justinffs** [matt-filion/serverless-external-s3-event#43]
Was just looking at my `yarn outdated` and this package has a 1.0.9 release while I am runing 1.0.7.  I don't see a changelog file and there is nothing in releases.  Is there a way to see the commits between 2 versions?  Thanks.

**Comment by matt-filion** [comment]
I'm not sure where 1.0.9 came from. I've deprecated a few versions back pointing everyone to the 2.0 version now at https://www.npmjs.com/package/serverless-plugin-existing-s3

There should also be a 1.0.10 version now that includes that as a callout at the top of the documentation.

**Comment by justinffs** [comment]
Thanks!
