### ISSUE TITLE
S3 deploy job failing in deploy step

### ISSUE THREAD

**Issue by adwaitkaley** [matt-filion/serverless-external-s3-event#61]
I am having issues with NPM 3.10.3 on node 6, this started recently 
Any thing new that released and broke the plugin ?

at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:886:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by matt-filion** [comment]
Not enough information to diagnose. NPM6 is also out of support. Recommend upgrading to the latest LTS of Node.
