### ISSUE TITLE
Missing policy s3:PutBucketNotification

### ISSUE THREAD

**Issue by efortes** [matt-filion/serverless-external-s3-event#74]
In the documentation should be explanation that the user running the deployment need to have `s3:PutBucketNotification` policy. Without this you always get an access denied. Please include this in the documentation. I had to debug the code to find out that this is needed.

**Comment by clifff** [comment]
Ran into the same problem and this ticket helped me figure it out - also had to add `s3:GetBucketNoficaiton` permissions to the deploying user.

**Comment by efortes** [comment]
@clifff yes I already had an idea that this would help someone :).

**Comment by matt-filion** [comment]
Pull request resolved this today. Thanks for opening the issue!

**Comment by efortes** [comment]
@matt-filion thank you very much for fixing.
