### ISSUE TITLE
Send events from existing S3 bucket to SQS

### ISSUE THREAD

**Issue by exiiluca** [matt-filion/serverless-external-s3-event#80]
How would you send an S3 event to an SQS queue instead of lambdas?
The SQS resource is created within my serverless config, but I can't figure out how to link S3 and SQS.
In my case I configured SQS to trigger lambdas and I'd like to queue S3 events through SQS.

Thanks

**Comment by matt-filion** [comment]
This is likely a more appropriate solution to your problem than this plugin.
https://medium.com/@windix/aws-s3-bucket-notification-to-sqs-queue-via-sns-topic-walk-trough-36c0a2ba6cde
