### ISSUE TITLE
Why this PR is not on 2.0 branch?

### ISSUE THREAD

**Issue by ndeitch** [matt-filion/serverless-external-s3-event#89]
Hi Matt,
Why the pull request 31 is not on 2.0 branch?
I think it's a very nice feature, because, We have to rebind the events after each deploy, today We are doing it manually.

**Comment by matt-filion** [comment]
The structure of the code is completely different across the two branches. Its probably worth updating to 2.0 if you would like this feature.

**Comment by ndeitch** [comment]
I'm sorry but I didn't get what you mean, in branch 2.0 this feature is not available, right? is that ok if I open a PR with this suggestion?
thanks!
